name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.2.2
  get_it: ^8.0.1
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/


flutter_native_splash:
  color: "#0B1E2D"
  image: "assets/images/splash.png"

flutter_launcher_icons:
  image_path: "assets/icons/launch_icon.jpeg"
  android: true
  ios: true

